// import './globals.css'
import "../styles/style.scss";
import { jost, serif, playfair, montserrat } from "@/utils/fonts";
import MiddleGrid from "@/components/grid/middleGrid";

export const metadata = {
  title: "NavigationBD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${serif.variable} ${playfair.variable} ${montserrat.variable}`}
      >
        <MiddleGrid />
        <div className="main">{children}</div>
      </body>
    </html>
  );
}
