// import './globals.css'
import { Inter } from "next/font/google";
import { jost, serif, playfair, montserrat } from "@/utils/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NavigationBD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${serif.variable} ${playfair.variable} ${montserrat.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
